export const featuresDetailsEn1 = {
    title: "Upload your item details",
    caption: "Begin the process by entering the details of the item you wish to sell. Choose the brand, specific category, and other relevant data that will make your listing more precise and appealing to potential buyers."
}

export const featuresDetailsEn2 = {
    title: "AI-generated Description",
    caption: "Once the data is entered, Describify's powerful artificial intelligence engine kicks into gear. Using advanced algorithms, it generates a perfect description for your listing. Let the AI take care of the heavy lifting, saving you time and effort in crafting the description."
}

export const featuresDetailsEn3 = {
    title: "Copy and Paste the Description",
    caption: "With the generated description, your task is simple: just copy and paste it into the selling platform of your choice. It's that easy! In a few moments, your listing will be ready to attract the attention of potential buyers with an accurate and engaging description."
}

export const featuresDetailsEn4 = {
    title: "Sell and Profit",
    caption: "Now comes the most rewarding moment: selling your products and making a profit! With an accurate and detailed description generated by Describify, you're ready to capture the interest of buyers and successfully close the sale. Get ready to see your items fly off the virtual shelves as you accumulate profits."
}
